apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/seolman/homelab.git
    targetRevision: HEAD
    path: infra/overlays/prod/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
