#cloud-config
users:
  - name: seolman
    lock_passwd: true
    shell: /usr/bin/bash
    groups: users, sudo
    ssh_authorized_keys: 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOlV/mXIFP5C2FIXrkv49i6VmUQrB/hlZ2m/gfprWNMi tjfehdgns@gmail.com"

