apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: storage-configuration
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    config.env: AgA2A3LcbAXz7vBRVx0oY6C/dMBDpIGy62fhlFaAFAdP0P8Dj+GWfsByp3mU7F5F2EQTHyB0hCm7e5NQRcIjjJwcs353ZKDoWjc7pTQ96j5+kQx0h3AKaPxDHY7VS8JfvwJfNuOHoE2Ra4PQEYoFTNzeTP3XXVvCVnV46oi56QGmy3yVbaxKM4uj30AAN6Mhl9HK8Dxce/mbFpBsVUYCkDp2DKoi9ZdmXRfROSt3Rg4vVfwD0eR2OA5ewTEoe4SKjnWjrbvJCwwAD9vZoD25kdZ6oyDWuPa6IdK1PheVev0H1W0TJT2V6yyrcwmUvd0bS7NUMQb+fn5y0lKsUc2I5ePaWGd0OYu9oBigKPebyOw6FmHFFGio0ZmE6NVgOAsCicmD9Om0iwTVzvRKL/38wfKyRfOYf2fEs/I+2HEbxsbrDVWw4L1LxFUQP4ub12FWKILW//yJbPQdgTNpv7UKt2o8le4U89A0jXi9Pwx0FUMqW/r/C+JgHRTAVqjPHLDSXjXkQYSZ3bAcyacUqDd5vk18QAkqSUhWZ/py4OhZzWbVEepwt0HuWUb5006YLo89d1ZVHOENvOOgWwCIlkSDYFm0ao6Y7xZxe8BSe2sgpqYmekh646+cvlHIWO2efKk9jACNNv8HJpSXfYWyp0iTVC5Bpco+ND+sECAbfCN/V7yCG8vOuBt1V8YT6NxZJ7VmVZB80ceTOqgjNwbwHsV3wUxJWfjOQo6CcmNLjzMdJtSTAgaMsP8yaS45wn//oaYu45uK5IX/oPrNV2Zv039lHYUCSQ0T8AtU3GJb+L8hvUnRdZv949+JcrsJ9iOXZHmujslpb3qpr+mbJN6B1AdnEPg31MiIuovrgF951khjPhaeRnTQKDn07H9s0BVE1oDHUgz2PBnklf/WVY8PNK03JhkZrLYrFS8qJkkMlHuqUtbzVImzPJTVr/qaO+t3TA7psQtjSIsaRZNxhoVw9ifXe0QdiupxLp0FmFeqNtQ9lbx/qwILOMjrng0SG0xm5yU3fJf+TLbRovrWcH0vHT6WDT4iy4aCBw==
  template:
    metadata:
      name: storage-configuration
      namespace: database
