apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: main-tenant
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  users:
    - name: storage-user
  configuration:
    name: storage-configuration
  requestAutoCert: false
  pools:
    - servers: 4
      name: pool
      volumesPerServer: 1
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: longhorn
