---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBvwkEy8BU58T7rQjdtKbK50xYmnxYG4XOFjA5O1kOnDIADSK06HCFI4Sl20HLjlJQF47jqTbbFmbRuIJusbAbWAdE5l/+e36ONDnXq0wGVKNEwL9PybaL6HlKplCIBy79rMe3wzlvzKMnM4ujDtL2yOPeBc9oIFKQBjbuseVJq4k03e5lLJayNUDzOF2BBzEW/0anXZgMpxNJvs4zAd2pPcsLJdS4j+2ZvlgB48UXO0rmKVGX0eGF2Ab8FWltgaAR91uD+Rh13RK5mLR61it0I52cPRn9OjdrZNWHmcSdjgVAHrUOU/wc9F0JoHJCxJc/+ZLeODRJM3EWCAfNZSDX/NmxWGw+PD+PBkYOp2t7Eyx9Pon3MJbBqDdcZ6UFuyfSmb9ly74643AO/OQtwobGrSVng4FoZ4pjxpWzmK4BR/Ex7wH/uj47H+lslsLHkl9EbmbEV5bRy2jpDYf6Id3mIUKSEKctycvGs1JWmZCpgxJvOgYp8Z+t6pYWDJv3nD5o15yqcT4AsN12UBlkIeMQ+ysZ+dtBzknpW+wk/QADoYeeZOuXSc5Rln0BRRr1ECAOSclQywLGlNBVzCxvcwu7oGIzUuA3IxPVCs3ltq7vyjpKx4CIEhMyejXLBPjDTJSFPI4m/bqPu7DepiHilmEkuXElzd1Gbe7n1+1CmD4xcSxvtGWwvITd5ppIwj4DitYc4I9AgneWth54Rdj3aAJhCOrlYTH5c9gQxVo+x1eAwSGYw3oPoDX8i
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
