apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAHpcqQJ+BvRs2k/py+pIMfD2lWjqZ8dsGfrHIbrYnf62HdkCM1cow4GMxw18eLrfSLoAk/+GyVHcw+u68D21gDllxXMoVc6mJMKPkjxdHr0Z3RdWjyVfnZQDG1gxBJ5qq66QfMyjqpxSlwZEtjxhWdMpXfrerSDIt38qGTVv1Y8iC5Io7jlCaTP1n+nY0+VzAE+k+T3xPEFlKX3SUqy6uzThDifXw3rd/LP5lPNw+CLn1eVo9t0+yN9k/sZ9KPt0vKicewiRfEaR3QKRdoPs5pvgp3EwJ6IteWiGvWOFhY9jlNpjeEFjaTfHEMU597ddxtnuxKVR4kGUgVw6ltKL/J/t5yuSyhpHVyenHgYm52g6YkKUvK25bfZDT4BtEiOLQfeVk9NZdNZku4d3qfhD85Wov0xuDsu2nipqW8u7D3mY/OeMkOce7C4nPeAmMy7x04VbJuSYe2A5+dq9kKRbaLqCI5K1XsBaEOKpUPC35MgMNAKTq1fALyh2i1+0Yrgx0swoBHeoMu0AopG+CdIvflCVz50ndmI1aN4akJpqcky/1wU3gXjaFLMGVOCEWvHWe1Tlmq2sCUKMNWC1x3SR7eZDXRRQs1l7z+pazpFtsCFae0voTPTWk8B36HZvmvqpmWTIxJQoSKWlodIU/KDffhtBxqZL742RG17VKG0a5gqAHX39963YJUi0P1jaQfphP6UIdarQRaiKn49oQUhfym95fdkdApkFDHcSbTYW54ukC2drFEVe26
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
