apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prod-db
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn
  # TODO backup
