apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nginx.seolman.dev
  dnsNames:
    - nginx.seolman.dev
