apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seolman-dev-wildcard-cert
  namespace: cert-manager
spec:
  secretName: seolman-dev-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.seolman.dev"
  dnsNames:
    - "*.seolman.dev"
